apiVersion: v1
kind: Service
metadata:
  name: myapp1-nodeport-service
spec:
  type: NodePort # ClusterIP # LoadBalancer
  selector:
    app: myapp1
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31280